sudo: required
services:
  - docker

before_install:
  - docker build -t amorino/docker-react -f Dockerfile.dev .

script:
  - docker run amorino/docker-react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "docker-test"
  bucket_path: "docker-react"
  on:
    branch: master